package com.qltd.backend.service;

import com.qltd.backend.entity.AnhTaiSan;
import com.qltd.backend.repositories.AnhTaiSanRepository;
import java.io.Serializable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Generated by Spring Data Generator on 10/06/2018
 */
@Component
public class AnhTaiSanService {

    private AnhTaiSanRepository anhTaiSanRepository;

    @Autowired
    public AnhTaiSanService(AnhTaiSanRepository anhTaiSanRepository) {
        this.anhTaiSanRepository = anhTaiSanRepository;
    }

}
