package com.qltd.backend.service;

import com.qltd.backend.repositories.ChucVuRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class ChucVuService {

	private ChucVuRepository chucVuRepository;

	@Autowired
	public ChucVuService(ChucVuRepository chucVuRepository) {
		this.chucVuRepository = chucVuRepository;
	}

}
