package com.qltd.backend.service;

import com.qltd.backend.repositories.CuaHangRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class CuaHangService {

	private CuaHangRepository cuaHangRepository;

	@Autowired
	public CuaHangService(CuaHangRepository cuaHangRepository) {
		this.cuaHangRepository = cuaHangRepository;
	}

}
