package com.qltd.backend.service;

import com.qltd.backend.repositories.DongTienRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class DongTienService {

	private DongTienRepository dongTienRepository;

	@Autowired
	public DongTienService(DongTienRepository dongTienRepository) {
		this.dongTienRepository = dongTienRepository;
	}

}
