package com.qltd.backend.service;

import com.qltd.backend.repositories.GhiNoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class GhiNoService {

	private GhiNoRepository ghiNoRepository;

	@Autowired
	public GhiNoService(GhiNoRepository ghiNoRepository) {
		this.ghiNoRepository = ghiNoRepository;
	}

}
