package com.qltd.backend.service;

import com.qltd.backend.repositories.GopVonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class GopVonService {

	private GopVonRepository gopVonRepository;

	@Autowired
	public GopVonService(GopVonRepository gopVonRepository) {
		this.gopVonRepository = gopVonRepository;
	}

}
