package com.qltd.backend.service;

import com.qltd.backend.repositories.NhanVienRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class NhanVienService {

	private NhanVienRepository nhanVienRepository;

	@Autowired
	public NhanVienService(NhanVienRepository nhanVienRepository) {
		this.nhanVienRepository = nhanVienRepository;
	}

}
