package com.qltd.backend.service;

import com.qltd.backend.repositories.TaiSanHopDongRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class TaiSanHopDongService {

	private TaiSanHopDongRepository taiSanHopDongRepository;

	@Autowired
	public TaiSanHopDongService(TaiSanHopDongRepository taiSanHopDongRepository) {
		this.taiSanHopDongRepository = taiSanHopDongRepository;
	}

}
