package com.qltd.backend.service;

import com.qltd.backend.repositories.VayLaiRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class VayLaiService {

	private VayLaiRepository vayLaiRepository;

	@Autowired
	public VayLaiService(VayLaiRepository vayLaiRepository) {
		this.vayLaiRepository = vayLaiRepository;
	}

}
