package com.qltd.backend.service;

import com.qltd.backend.repositories.XaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 10/06/2018
*/
@Component
public class XaService {

	private XaRepository xaRepository;

	@Autowired
	public XaService(XaRepository xaRepository) {
		this.xaRepository = xaRepository;
	}

}
